(when (require 'flymake-python-pyflakes nil t)
  (add-hook 'python-mode-hook 'flymake-python-pyflakes-load)
  )
(when (require 'highlight-indent-guides nil t)
  (add-hook 'python-mode-hook 'highlight-indent-guides-mode)
  (add-hook 'web-mode-hook 'highlight-indent-guides-mode)
  (setq highlight-indent-guides-method 'column)
  (setq highlight-indent-guides-auto-odd-face-perc 15)
  (setq highlight-indent-guides-auto-even-face-perc 30)
  (setq highlight-indent-guides-auto-character-face-perc 20)
  )
